# Generated by Django 4.2.2 on 2025-08-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('PAID', 'Paid'), ('COD', 'Cash on Delivery')], default='PAID', max_length=10),
        ),
    ]
