# Generated by Django 4.2.2 on 2025-07-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_chatsession_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
