# Generated by Django 5.2.3 on 2025-06-21 19:07

import django.db.models.deletion
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True, editable=False, max_length=22, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "stock_count",
                    models.CharField(
                        blank=True, default="10", max_length=100, null=True
                    ),
                ),
                ("weekly_sales", models.IntegerField(default=0)),
                ("last_week_sales", models.IntegerField(default=0)),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "price_adjustment_step",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
                ),
                ("demand_threshold_high", models.IntegerField(default=20)),
                ("demand_threshold_low", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "demand_high",
                    models.IntegerField(
                        default=100, verbose_name="High Demand Threshold"
                    ),
                ),
                (
                    "demand_low",
                    models.IntegerField(
                        default=20, verbose_name="Low Demand Threshold"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("weekly_sales", models.IntegerField()),
                ("demand_score", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_changes",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ProductSalesHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("weekly_sales", models.IntegerField()),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stock_count", models.IntegerField(default=0)),
                ("demand_score", models.FloatField(default=1.0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_history",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
